clear_heatmap:
  target:
    device:
      manufacturer: EverythingSmartTechnology
      model: Everything Presence Pro
    entity:
      device:
        manufacturer: EverythingSmartTechnology
        model: Everything Presence Pro
