sensor:
  - platform: scd4x
    i2c_id: bus_b
    id: scd40
    co2:
      name: "CO2"
      id: "co2"
      on_value:
        then:
          - if:
              condition:
                lambda: 'return id(led_mode_select).current_option() == "Environmental" || id(led_mode_select).current_option() == "Environmental + Presence";'
              then:
                - script.execute: control_leds
    automatic_self_calibration: false

i2c:
  - id: bus_b
    scl: GPIO16
    sda: GPIO4
    scan: true

button:
  - platform: template
    name: "Calibrate CO2"
    id: calibrate_scd40
    on_press:
      - scd4x.perform_forced_calibration:
          value: 419
          id: scd40

select:
  - platform: template
    name: "CO2 Log Level"
    id: log_level_co2
    icon: "mdi:math-log"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_option: "Warning"
    options:
      - "None"
      - "Error"
      - "Warning"
      - "Info"
      - "Debug"
    on_value:
      then:
        - lambda: |-
            esp_log_level_t level;
            if (x == "None") level = ESP_LOG_NONE;
            else if (x == "Error") level = ESP_LOG_ERROR;
            else if (x == "Warning") level = ESP_LOG_WARN;
            else if (x == "Info") level = ESP_LOG_INFO;
            else level = ESP_LOG_DEBUG;
            esp_log_level_set("scd4x", level);
